### ISSUE TITLE
ParseDN bug

### ISSUE THREAD

**Issue by nakisen** [merlinz01/ldapserver#1]
If an invalid name value comes from the client, panic occurs and the application is terminated. This could be considered a bug.

```
// req.Name = onepartstring
dn, err := ldapserver.ParseDN(req.Name)
```

> panic: runtime error: index out of range [1] with length 1

```
func ParseDN(s string) (DN, error) {
	var dn DN
	for _, rdn := range splitRDNs(s) {
		var r RDN
		for _, attr := range splitAttrs(rdn) {
			parts := splitAttr(attr)
			value, err := DecodeRDNAttributeValue(parts[1])  <<<< ERROR
			if err != nil {
				return nil, err
			}
			r = append(r, RDNAttribute{Type: parts[0], Value: value})
		}
		dn = append(dn, r)
	}
	return dn, nil
}
```

**Comment by merlinz01** [comment]
Thanks for catching that. Can you provide an example of the invalid input?

**Comment by nakisen** [comment]
Any string without a "key=value" pair will cause an error.

```
dn, err := ldapserver.ParseDN("test")
```

**Comment by merlinz01** [comment]
I have updated the code to handle that case and added tests for it. You can update to v0.0.16.

It should return an ErrInvalidDN.
